language: en
pipeline:
- name: MitieNLP
- name: MitieTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
  token_pattern: None
- name: MitieFeaturizer
  pooling: mean
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: MitieEntityExtractor
- name: DIETClassifier
  entity_recognition: false
  epochs: 100
- name: EntitySynonymMapper
- name: MitieIntentClassifier
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
